### ISSUE TITLE
Periodic jobs is now outdated

### ISSUE THREAD

**Issue by brkn** [fractaledmind/euruko-2024#2]
See: https://github.com/rails/solid_queue/pull/338

From my understanding it should change from this at [workshop/07-adding-solid-queue.md](https://github.com/fractaledmind/euruko-2024/blob/main/workshop/07-adding-solid-queue.md)

### Right now

Mentions
> We can do this by defining a recurring task in the `config/solid_queue.yml` file

Then

```yaml
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        periodic_litestream_backup_verfication_job:
          class: Litestream::VerificationJob
          args: []
          schedule: every day at 1am EST
```

### Should be changed as

Mentions
> We can do this by defining a recurring task in the `config/schedule.yml` file

Then

```yaml
periodic_litestream_backup_verfication_job:
  class: Litestream::VerificationJob
  args: []
  schedule: every day at 1am EST
```
